### ISSUE TITLE
What is inscription balance? 

### ISSUE THREAD

**Issue by Abqna** [unisat-wallet/extension#101]
how to transfer BTC out of the inscription balance?

**Comment by GGG888GGG** [comment]
Unisat doesn't allow users to spend the sats the inscriptions hold in order to prevent them from unintentionally spending inscriptions as gas fee, if it happens, they will permanently lose their inscriptions, some are valuable.

so, are you 100% sure you don't want to keep inscriptions anymore? If so, changing inscriptions to BTC, not only you will lose inscriptions, but also you will pay much more gas fee due to transferring many small uxtos from 546 sats inscriptions(because it will increase the virtual size in the txn), you will get very small funds in the end.

Based on the above, if you insist on giving up the inscriptions, you may refer to https://www.howusedapps.com/how-to-exchange-inscriptions-for-bitcoin/ and withdraw them to exchange.

In addition, if a single inscription holds much more sats especially(generally an inscription holds 546 sats), you could use Split(choose the inscription and you will see Split button below) in unisat wallet to split extra bitcoins, this way will keep the original inscription.
@Abqna
