### ISSUE TITLE
How to verify legacy address signatures signed using window.unisat.signMessage?

### ISSUE THREAD

**Issue by msmalley** [unisat-wallet/extension#11]
There seems to be no examples or documentation on how to verify messages that are signed using `window.unisat.signMessage`

I am specifically trying to sign messages with legacy addresses - not with BECH32 or taproot ones and yet the signature returned cannot be verified by bitcoin-core RPC or by bitcoinjs.Message.verify.

Any help would be much appreciated :-)

**Comment by thienma1258** [comment]
also wondering how to doing that too

**Comment by cloud6605** [comment]
please search "sign" in  https://docs.unisat.io/dev/unisat-wallet-api, then you can find the example.

**Comment by ArbitronNL** [comment]
> please search "sign" in https://docs.unisat.io/dev/unisat-wallet-api, then you can find the example.

@GGG888GGG @cloud6605 We hereby request this issue to be re-opened, since it is not about "how" to sign a message, but the fact that the created signature is invalid: `cannot be verified by bitcoin-core RPC or by bitcoinjs.Message.verify`. 

---

As a matter of fact, we've determined the same issue in https://github.com/BitonicNL/verify-signed-message/issues/3#issuecomment-1597101994. As a TLDR, UniSat is using the incorrect recovery flags for addresses, causing the signatures to not work anywhere that the uses the official specification (Electrum, Bitcoin Core, Trezor, etc).
