### ISSUE TITLE
"networkChanged" event not working?

### ISSUE THREAD

**Issue by gndelia** [unisat-wallet/extension#211]
In my app, I listen for both `accountsChanged` and `networkChanged` events.

I do so by running

```ts
window.unisat.on('accountsChanged', handler)
window.unisat.on('networkChanged', handler)
```

While both used to work, today I noticed that `networkChanged` event isn't fired. Has something changed? My code detects when accounts have changed, but `networkChanged` does not fire the handler (ever)

**Comment by huanniangstudio** [comment]
Please use `chainChanged` event.
`window.unisat.on('chainChanged', handler)`

Due to our support for more networks, such as fractal(mainnet), testnet4(testnet), and signet(testnet), a new method is required to properly identify the current chain. 

We will fix the `networkChanged` event shortly, but it is not recommended to use.

**Comment by gndelia** [comment]
I tried with `window.unisat.on('chainChanged', handler)` and it worked. Thanks @huanniangstudio !
