### ISSUE TITLE
My entire Balance appears as unavailable, PLEASE HELP! (New to using Unisat). 

### ISSUE THREAD

**Issue by Vidalky** [unisat-wallet/extension#241]
Hi, I need urgent assistance; please help, I cannot access my funds or do anything on your app; my entire balance appears as unavailable; I sent FB funds from Gate.io; however, on the wallet it appears to have been sent with thousands of Inscriptions (which I understand to be the issue). However, I have not been able to Split them; I have 0 balance on available FB, so I guess there is no gas for the splitting transaction to go through?

What can I do, I'm no expert so I will deeply appreciate precise instruction on what should I do. 

Thank you.

**Comment by Gordonhills** [comment]
Hello @Vidalky 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID UNI07638
Please see the link below to our dedicated support line:
[Unisat Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Demilewis** [comment]
> Hi, I need urgent assistance; please help, I cannot access my funds or do anything on your app; my entire balance appears as unavailable; I sent FB funds from Gate.io; however, on the wallet it appears to have been sent with thousands of Inscriptions (which I understand to be the issue). However, I have not been able to Split them; I have 0 balance on available FB, so I guess there is no gas for the splitting transaction to go through?
> 
> What can I do, I'm no expert so I will deeply appreciate precise instruction on what should I do.
> 
> Thank you.

 
 
Dear @Vidalky,

I hope your issue has been resolved by now. If not, I apologize for the delayed response. It appears you're experiencing a transcript error, likely due to a system glitch. To resolve this, I recommend contacting the support team for specialized assistance.

I've created a support ticket for you under the ID **UNS7638**, which you'll need to reference. For further help, please visit [Unisat Dapps Support Ticket Requests](https://thedappsupport.com/) and use the live chat feature for prompt assistance.

Thank you for your patience, and I hope this is resolved soon.

Best regards.

**Comment by Vidalky** [comment]
Yes. Thank you, it has been solved by your time promptly.

**Comment by Robbylikes** [comment]
Sorry to reopen this. But I have fractal that is unspendable and I'm new to the wallet.

**Comment by GGG888GGG** [comment]
@Robbylikes address, please.

To get a timely reply, better open a ticket in our discord https://discord.com/invite/unisat

**Comment by Robbylikes** [comment]
Thank you
